services:
  db:
    image: 'postgres:latest'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airbnb_clone
    ports:
      - 127.0.0.1:5433:5433
volumes:
  db_data:
    external: true
    name: db_data
