logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.diegodsoliveira.airbnb_clone_back: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnbclone?autoreconnect=true
    username: postgres
    password: postgres
    # url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    # username: ${POSTGRES_USER}
    # password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: public
  liquibase:
    contexts: prod
    default-schema: public
